### ISSUE TITLE
Suggestion: add "xx" keyword

### ISSUE THREAD

**Issue by CAD97** [DoumanAsh/xxhash-rust#14]
I nearly didn't find this crate

**Comment by DoumanAsh** [comment]
uhm `xxh` and `xxhash` should find this crate pretty quickly
I dunno what `xx` keyword would even represent as search query.

Hashing function name is `xxhash` so search is obviously would be done by it

**Comment by CAD97** [comment]
The problem is I was searching "xx hash" (I am not a hash algorithm expert), and that doesn't show any of the XXHash algorithm implementations (except for a very recent xx-hash crate).
