### ISSUE TITLE
Enhancement: Add a simple command-line interface for ease of use 

### ISSUE THREAD

**Issue by sify21** [DoumanAsh/xxhash-rust#25]
I suggest add a command-line interface under `src/bin`. Sometimes I just want to use xxhash as a tool, in older distributions `xxhsum` is not available, such as ubuntu before 18.04.

**Comment by DoumanAsh** [comment]
I made separate binary for my own needs https://github.com/DoumanAsh/xxhash-cli
But I didn't really bother to tidy it up, if you want, feel free to.

But I'm not going to add any extra code to this crate

**Comment by sify21** [comment]
Hi @DoumanAsh , how can I make `xxhash-cli` to output the same results as the c-version `xxhsum`, so that I can compare them?

**Comment by DoumanAsh** [comment]
I never used `xxhsum` so I cannot know, I would suggest to check source code how to prints and modify `xxhas-cli` source code to do it.
I just write hash as integer but you could write it in any format using standard formatting in Rust:
https://doc.rust-lang.org/std/fmt/
