### ISSUE TITLE
available for ARM?

### ISSUE THREAD

**Issue by evbo** [DoumanAsh/xxhash-rust#27]
Just judging by the readme, it reads "suitable for X86..." or "suitable for X86_64...". What about ARM processors, which is recommended?

The xxhash github for the C implementation says it's highly portable, so thought I could run this on ARM.

**Comment by DoumanAsh** [comment]
@evbo It only talks about hardware accelerations.
If there is no hardware acceleration (I didn't implement NEON instructions yet) then it fallbacks to default scalar implementation.
So it should work without issue on any 32bit processor
