### ISSUE TITLE
Add Arm's NEON vectorization

### ISSUE THREAD

**Issue by eirnym** [DoumanAsh/xxhash-rust#34]
Could you please enable optimizations for macbooks by default as you've did for x86_64 CPUs

**Comment by DoumanAsh** [comment]
Please understand that current implementation only supports AVX2 and SSE2, therefore it is impossible to enable by default, as there is no NEON implementation

Now for matter of default in general
NEON cannot be assumed to be default in general, but I believe all mac OS chips do so, so in theory I could assume that, but only for Mac OS.

Problem is that when I started this library NEON support in Rust's std was lacking and I'm not sure if they filled gaps yet to implement it
I will try to take a look again later

**Comment by eirnym** [comment]
Most of features supported by LLVM [has been implemented](https://github.com/rust-lang/stdarch/issues/148).

Documentation also describes many neon instructions, some of them available since Rust 1.59.0

https://doc.rust-lang.org/core/arch/arm/index.html
https://doc.rust-lang.org/core/arch/aarch64/index.html

**Comment by eirnym** [comment]
I have macOS M2 laptop:

```shell
$ rustc --print cfg
debug_assertions
panic="unwind"
target_arch="aarch64"
target_endian="little"
target_env=""
target_family="unix"
target_feature="aes"
target_feature="crc"
target_feature="dit"
target_feature="dotprod"
target_feature="dpb"
target_feature="dpb2"
target_feature="fcma"
target_feature="fhm"
target_feature="flagm"
target_feature="fp16"
target_feature="frintts"
target_feature="jsconv"
target_feature="lor"
target_feature="lse"
target_feature="neon"
target_feature="paca"
target_feature="pacg"
target_feature="pan"
target_feature="pmuv3"
target_feature="ras"
target_feature="rcpc"
target_feature="rcpc2"
target_feature="rdm"
target_feature="sb"
target_feature="sha2"
target_feature="sha3"
target_feature="ssbs"
target_feature="vh"
target_has_atomic="128"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="macos"
target_pointer_width="64"
target_vendor="apple"
unix
```

**Comment by eirnym** [comment]
my test:

```toml
```

**Comment by DoumanAsh** [comment]
Well it is good that Mac has Neon enabled by default
I will merge and release new version later

**Comment by DoumanAsh** [comment]
Release 0.8.9 with Neon
