### ISSUE TITLE
benchmarking xxh3 vs ahash for use in std HashMap

### ISSUE THREAD

**Issue by feature-engineer** [DoumanAsh/xxhash-rust#40]
Hi, I've read your claim that the benchmarks performed by ahash were not using xxh3 in an optimal manner, and I would like to create a benchmark which would use xxh3 correctly.

I've written these two very simple functions to benchmark:

```rust
 pub fn use_ahash(v: &str) {
    let mut hash = ahash::AHashMap::<&str, i64>::default();
    hash.insert(v, 1);
    assert_eq!(*hash.get(v).expect("Not found"), 1);
    assert_eq!(*hash.get("Does not exist in hash table").unwrap_or(&-1), -1);
}

pub fn use_xxh(v: &str) {
    let mut hash = HashMap::<&str, i64, xxh3::Xxh3Builder>::default();
    hash.insert(v, 1);
    assert_eq!(*hash.get(v).expect("Not found"), 1);
    assert_eq!(*hash.get("Does not exist in hash table").unwrap_or(&-1), -1);
}
```

Is this the correct use of xxh3 for usage with HashMap?

**Comment by DoumanAsh** [comment]
The problem is not how you benchmark, but std's HashMap having inefficient interface
It creates hasher for every hash while better approach would be to use oneshot function.
And as xxh3's state is very complex creating full state every time is expensive call

So generally my implementation of xxh is not suitable for use in std's HashMap
You're supposed to create [state](https://docs.rs/xxhash-rust/0.8.10/xxhash_rust/xxh3/struct.Xxh3.html) once and re-use it every time by calling [reset](https://docs.rs/xxhash-rust/0.8.10/xxhash_rust/xxh3/struct.Xxh3.html#method.reset)

**Comment by DoumanAsh** [comment]
Also hashing integers/small strings generally irrelevant benchmark

**Comment by feature-engineer** [comment]
Maybe it'd make sense to have a singleton class which returns the single instance whenever its created and pass that to the HashMap?

**Comment by DoumanAsh** [comment]
There is no purpose in trying to work around bad interface of std library

And no, you cannot just return have singleton as then you need to worry about concurrency

**Comment by feature-engineer** [comment]
Ok, I've found a nice workaround:

```rust

struct Xxh3StaticHashBuilder {}

struct Xxh3StaticWrapper {
    _written: u64,
}

impl Hasher for Xxh3StaticWrapper {
    fn finish(&self) -> u64 {
        self._written
    }

    fn write(&mut self, bytes: &[u8]) {
        self._written = xxh3::xxh3_64(bytes)
    }
}

impl std::hash::BuildHasher for Xxh3StaticHashBuilder {
    type Hasher = Xxh3StaticWrapper;
    fn build_hasher(&self) -> Self::Hasher {
        Xxh3StaticWrapper{ _written: 0 }
    }
}
```

Then using the std HashMap like this
```rust

pub fn use_xxh(v: &str) {
    let mut hash = HashMap::with_hasher(Xxh3StaticHashBuilder{});  // HashMap::<&str, i64, xxh3::Xxh3Builder>::default();
    hash.insert(v, 1);
    assert_eq!(*hash.get(v).expect("Not found"), 1);
    assert_eq!(*hash.get("Does not exist in hash table").unwrap_or(&-1), -1);
}
```

Is quite fast (faster than ahash if the string is more than ~200 characters long).

**Comment by DoumanAsh** [comment]
yes, but note that this solution only works well if you use types where Hash implementation writes once
Otherwise you'll have incorrect result so you should only use it in specialized cases (strings, bytes, integers)

**Comment by feature-engineer** [comment]
I see. I guess a HashMap isn't the best usecase for xxh anyway, as plain keys tend to be small objects, and nested keys require the instance to update and can't call the hash function one.

Feel free to close this issue, and thanks for your time.
