### ISSUE TITLE
Hashing a (large) file

### ISSUE THREAD

**Issue by JeffSpies** [DoumanAsh/xxhash-rust#41]
Hi, there! My understanding is that one way to hash a file is by using `io::copy`--that way a digest can be calculated over a stream; for example, as described [here](https://github.com/RustCrypto/hashes):

````rust
let mut file = fs::File::open(&path)?;
let mut hasher = Sha256::new();
let n = io::copy(&mut file, &mut hasher)?;
let hash = hasher.finalize();
````
Have you considered adding the [Write trait](https://doc.rust-lang.org/std/io/trait.Write.html), or do you have a preferred method of hashing files?

Thanks!

**Comment by DoumanAsh** [comment]
I can add it, it is not really hard to do

**Comment by DoumanAsh** [comment]
I release 0.8.11 which includes `std` feature that enables `io::Write` implementation on all hashers
